# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basicUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 820)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #FFFFFF;\n"
"border: transparent;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vidwidget = QtWidgets.QWidget(self.centralwidget)
        self.vidwidget.setGeometry(QtCore.QRect(80, 40, 650, 450))
        self.vidwidget.setStyleSheet("background-color: orange;")
        self.vidwidget.setObjectName("vidwidget")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(180, 610, 450, 71))
        font = QtGui.QFont()
        font.setFamily("Archivo")
        font.setPointSize(20)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("background: rgba(255, 255, 255, 0.3)")
        self.statusLabel.setObjectName("statusLabel")
        self.prompt = QtWidgets.QLabel(self.centralwidget)
        self.prompt.setGeometry(QtCore.QRect(65, 510, 680, 40))
        font = QtGui.QFont()
        font.setFamily("Archivo")
        font.setPointSize(18)
        self.prompt.setFont(font)
        self.prompt.setStyleSheet("background: rgba(255, 255, 255, 0.3)")
        self.prompt.setObjectName("prompt")
        self.allowButton = QtWidgets.QPushButton(self.centralwidget)
        self.allowButton.setGeometry(QtCore.QRect(65, 590, 300, 120))
        font = QtGui.QFont()
        font.setFamily("Archivo")
        font.setPointSize(20)
        self.allowButton.setFont(font)
        self.allowButton.setStyleSheet("background-color: #D0E2FF; ")
        self.allowButton.setAutoDefault(False)
        self.allowButton.setObjectName("allowButton")
        self.denyButton = QtWidgets.QPushButton(self.centralwidget)
        self.denyButton.setGeometry(QtCore.QRect(470, 590, 300, 120))
        font = QtGui.QFont()
        font.setFamily("Archivo")
        font.setPointSize(20)
        self.denyButton.setFont(font)
        self.denyButton.setStyleSheet("background-color: #D0E2FF; ")
        self.denyButton.setObjectName("denyButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(345, 5, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Archivo")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName("menubar")
        self.menuFILE = QtWidgets.QMenu(self.menubar)
        self.menuFILE.setObjectName("menuFILE")
        self.menuCredits = QtWidgets.QMenu(self.menubar)
        self.menuCredits.setObjectName("menuCredits")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuFILE.addAction(self.actionStart)
        self.menuFILE.addAction(self.actionexit)
        self.menubar.addAction(self.menuFILE.menuAction())
        self.menubar.addAction(self.menuCredits.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Lock Security System"))
        self.statusLabel.setText(_translate("MainWindow", "Detecting"))
        self.prompt.setText(_translate("MainWindow", "This person is not authorized. Give permission to open the door."))
        self.allowButton.setText(_translate("MainWindow", "ALLOW"))
        self.denyButton.setText(_translate("MainWindow", "DENY"))
        self.label.setText(_translate("MainWindow", "Live Feed"))
        self.menuFILE.setTitle(_translate("MainWindow", "File"))
        self.menuCredits.setTitle(_translate("MainWindow", "Credits"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionexit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
